import {
  HomeIcon,
  UserIcon as HiUserIcon,
  FolderIcon,
  TagIcon,
  CubeIcon,
  CalendarIcon,
  BuildingOfficeIcon,
  ChartBarIcon,
  BriefcaseIcon,
  UserCircleIcon,
  DocumentTextIcon,
  CheckCircleIcon,
  TruckIcon,
  WrenchScrewdriverIcon,
  ClipboardDocumentListIcon,
  PlusCircleIcon,
  ShoppingCartIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  CreditCardIcon,
  BanknotesIcon,
  ArrowPathIcon,
  BookOpenIcon,

} from "@heroicons/react/24/outline";
import { ElementType } from "react";
import { 
  TbCategory, 
  TbSourceCode, 
  TbBriefcase, 
  TbBuildingBank, 
  TbCoin,
  TbPalette, 
  TbColorSwatch, 
  TbBrush,
  TbTruck,
  TbTools,
  TbList,
  TbPlus,
  TbReceipt,
  TbReceiptOff,
  TbCash,
 TbBox,
  TbExchange,
  TbBook,
  TbFileInvoice,
  TbWallet,
  TbCreditCard,
  TbBuildingBank as TbBank,
  TbArrowsExchange,
  TbNotebook,
  TbReport,
  TbReceiptTax,
  TbReceipt2,
} from "react-icons/tb";

import DashboardsIcon from "@/assets/dualicons/dashboards.svg?react";
import SettingIcon from "@/assets/dualicons/setting.svg?react";


export const navigationIcons: Record<string, ElementType> = {
  dashboards: DashboardsIcon,
  user: TbBriefcase,
  settings: SettingIcon,
  "dashboards.home": HomeIcon,
  "settings.general": HiUserIcon,
  "settings.appearance": TbPalette,
  master: FolderIcon,
  category: FolderIcon,
  brand: TagIcon,
  model: CubeIcon,
  year: CalendarIcon,
  color: TbPalette,
  variant: CubeIcon,
  showroom: BuildingOfficeIcon,
  leadbuilder: ChartBarIcon,
  account: BuildingOfficeIcon,
  employee: HiUserIcon,
  broker: BriefcaseIcon,
  enquirysettings: TbCategory,
  enquirytype: DocumentTextIcon, 
  enquirysource: TbSourceCode, 
  profession: UserCircleIcon, 
  banker: HomeIcon, 
  finance: TbCoin, 
  enquirystatus: CheckCircleIcon,
  item: ClipboardDocumentListIcon, 
  tractor: TruckIcon,               
  accessories: WrenchScrewdriverIcon, 
  purchase: ShoppingCartIcon,
  "purchase-tractor": TbTruck,
  "purchase-accessories": TbTools,
  
  // ✅ Accounting Icons (using valid icons)
  accounting: TbBuildingBank,
  debitnote: TbReceiptTax,      // Receipt with tax (debit/outgoing)
  creditnote: TbReceipt2,        // Receipt (credit/incoming)
  cashpayment: TbCash,
  cashreceipt: TbCash,
  bankpayment: TbBank,
  bankreceipt: TbBank,
  contra: TbArrowsExchange,
  journal: TbBook,
  tinven: TbBox,
};